spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gajun755/springbootcloudconfiguration.git
          search-paths:
           - '{application}'
          refresh-rate: 0
        default-label: master
      

server:
  port: 8085